###
POST http://localhost:4000/products-api/products
Content-Type: application/json

{
    "productName":"phone",
    "price":70000,
    "brand":"kidney"
}


###
POST http://localhost:4000/users-api/user
Content-Type: application/json

{
  "name": "akhilesh",
  "email": "a@gmail.com",
  "password": "dmart_shiva",
  "cart": []
}


###

GET http://localhost:4000/users-api/users

###
PUT http://localhost:4000/users-api/user-cart/user-id/698196d0f7d1cc908f93a15e/product-id/698196daf7d1cc908f93a160

###
GET http://localhost:4000/users-api/users
